clear 

% --------
% (c) Viktor Podolskiy & Evan Simmons, U Mass Lowell
% --------
% part of the photonic funnels project  
% post-processes and plots the data generated by funnelsAxialScript01.m
%
% reproduces part of Figs.1, 2b, and 3 from 
% Adv. Opt. Mater. v.8, 2001321 (2020); developed with partial support
% from the National Science Foundation, grant # 2004298
% --------

set(0, 'DefaultLineLineWidth', 2);
set(0, 'DefaultAxesFontSize', 18);

% load the data
rTop=0.25; %funnel geometry
rFit=1; 
hAu=3.2; 
fname=['./testAxial06.r=',num2str(rTop),'.hAu=',num2str(hAu),'.rFit=',num2str(rFit)]; 
sufMM='.zFit=1.dr=0.05.nMM.mat'; 
load([fname,sufMM]); 

% Fig.1: Effective Medium Theory plot
figure(1) 
clf 
plot(lamArr, real(epsZZArr), '-r',...
    lamArr, -imag(epsZZArr),':r',...
    lamArr, real(epsXYArr), '-k',...
    lamArr, -imag(epsXYArr), ':k')
box on
legend('Re(\epsilon_{zz})', 'Im(\epsilon_{zz})', ...
    'Re(\epsilon_\perp)','Im(\epsilon_\perp)','Location','NorthWest')
xlabel('Wavelength (\mum)')
ylabel('Re(\epsilon), Im(\epsilon)')
ylim([-75 100])


% Fig.2 Transmission 
figure(2) 
clf
plot(lamArr,tranArr)
box on 
xlabel('Wavelength (\mum)')
ylabel('Transmission (AU)')


% Fig.3: intensity plot, I(r), D_eff(lambda)
% resize final figure if needed


% parameters to use when analyze radial distribution of intensity
rMax=10; dr=0.025;
z0=4.1; 
thr=0; 
fract=1/exp(2); 
% calculate confinement radius (Deff=2*rExt)
rExtArr=0*lamArr; 
for ilam=1:length(lamArr)
    rExtArr(ilam)=rFrac(EELst3(:,:,ilam),rFun2,zFun2,rMax,dr,z0,fract); 
end 

% calculate 2D intensity profiles
ilam=find(lamArr==9.5); % find the wavelength of interest
intensityArr=EELst3(:,:,ilam); 
intensityArr=intensityArr.^2/max(max(intensityArr.^2)); %intensity =|E|^2

% calculate radial distribution of intensity
rPltLst=(0.01:0.01:3);
intensityR=interp2(rFun2,zFun2,intensityArr,rPltLst,z0+0*rPltLst); 
   
intensityArr=intensityArr.^(0.25); %rescale intensity for better color scheme

figure(3)
clf

% 2D intensity plot
subplot(1,3,1)
surf(rFun2,zFun2,intensityArr,'EdgeColor','none');     
view(2)
colormap hot
xlim([0 2])
ylim([1.5 6])
set(gca,'ColorScale','linear')
caxis([0 0.6])
hold on 
plot3(rPltLst,z0+0*rPltLst,1.5+0*rPltLst,'-w')
xlabel('r (\mum)')
ylabel('z (\mum)')

% radial distribution of intensity
subplot(1,3,2)
plot(rPltLst,intensityR/max(intensityR), '-k')
hold on 
plot([0 5], exp(-2)*[1 1], ':k','linewidth',1)
box on 
xlabel('r (\mum)')
ylabel('I(r)/I_{max}')
xlim([0 3])
set(gca, 'YScale','log')
ylim([5e-4 2])

% confinement scale 
subplot(1,3,3)
plot(lamArr,2*rExtArr)
xticks(4:2:12)
box on 
xlabel('Wavelength (\mum)')
ylabel('D_{eff} (\mum)')


